# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/baruunaylal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ulaanbaatar
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Google Translate API Configuration
# Cloud Console-??? ????? API Key-?? ??? ????????
google.api.key=YOUR_ACTUAL_GOOGLE_CLOUD_API_KEY_HERE

# JWT & Security
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# Google Social Auth (OAuth2)
google.client.id=355100419526-d9vhdu27i5ctm9m0fadbcgnht8gpi98r.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-id=355100419526-d9vhdu27i5ctm9m0fadbcgnht8gpi98r.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=YOUR_ACTUAL_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lhasvren79@gmail.com
spring.mail.password=riedhdengjibeemr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.timeout=5000

# Server & File Upload
server.port=8080
# ? CORS ????????? ????????, ??? ??????? ???????? ????????
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173,http://192.168.1.5:5173,https://khovd-aylal.vercel.app
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.baruunaylal.backend=DEBUG